### ISSUE TITLE
Unable to remove picture from cloudinary cloud storage and add back for EDIT method

### ISSUE THREAD

**Issue by ahaque98** [ahaque98/TheRedChamber#1]
Picture upload to **Cloudinary Image Storage** is successfull but not able to delete and upload a new one on the EDIT method in the MenuItem Controller.

**Comment by JamieMutabber** [comment]
# Announcement!

- [ Planned ] **Azure Blob Storage will be integrated for storing of images**
- [ Planned ] **Cloudinary integration will be removed. But user data will be available from Azur Blob Storage**

**Comment by ahaque98** [comment]
> # Announcement!
> * [ Planned ] **Azure Blob Storage will be integrated for storing of images**
> * [ Planned ] **Cloudinary integration will be removed. But user data will be available from Azur Blob Storage**

After a long meeting. We have planned to go with adding all these images locally. Which will not create any problems but after a few weeks in production we'll move to Azure Blob Storage.
